export default {
  NO_DATA_FOUND: require('../assests/Images/noDataFound.json'),
  INTRO1: require('../assests/Images/intro1.png'),
  INTRO2: require('../assests/Images/intro2.png'),
  INTRO3: require('../assests/Images/welcome.png'),
  LOGO: require('../assests/Images/Logo.png'),
  LOGIN: require('../assests/Images/login.png'),
  WELCOME: require('../assests/Images/welcome.png'),
  SIGNUP: require('../assests/Images/signup.png'),
  OTP: require('../assests/Images/otp.png'),
  CREATE_PASSWORD: require('../assests/Images/createpassword.png'),
  FORGET_PASSWORD: require('../assests/Images/forgetpassword.png'),
  LOCATION: require('../assests/Images/location.png'),
  BUY: require('../assests/Images/Buy.png'),
  RECEIVE: require('../assests/Images/receive.png'),
  SEND: require('../assests/Images/send.png'),
  SWAP: require('../assests/Images/swap.png'),

  ACHAIN: require('../assests/Images/Achain.png'),
  BINANCE_COIN: require('../assests/Images/BinanceCoin.png'),
  ETHERIUM: require('../assests/Images/Etherium.png'),
  BINANCE_COIN: require('../assests/Images/BinanceCoin.png'),
  BITCOIN_CASH: require('../assests/Images/BitcoinCash.png'),
  TETHER: require('../assests/Images/Tether.png'),
  TRON: require('../assests/Images/Tron.png'),
  POUND: require('../assests/Images/Pound.png'),
  RIPPLE: require('../assests/Images/Ripple.png'),
  BALANCE_CARD: require('../assests/Images/balanceCard.png'),
  PLUS: require('../assests/Images/Plus.png'),
  PAYMENT: require('../assests/Images/Payment.png'),
  PAYMENT2: require('../assests/Images/payment2.png'),
  CROSS: require('../assests/Images/cross.png'),
  RIGHT: require('../assests/Images/right.png'),
  PROMOTION: require('../assests/Images/Promotion.png'),
};
